### ISSUE TITLE
无法竖屏+倍数播放+播放记录+备份功能

### ISSUE THREAD

**Issue by KoedaNagi** [heyanLE/EasyBangumi#10]
还有切换app后age动漫源会崩溃。。。。。

**Comment by heyanLE** [comment]
新功能得等我3.0重构完再开始开发，大概下下周能写完出个版本。动漫源崩溃的话下个版本一起带上

**Comment by heyanLE** [comment]
竖屏 get 倍数 get 记录 get 备份的话等下版本
