### ISSUE TITLE
播放源是只有樱花动漫能用吗，其他三个都看不了，加载出错

### ISSUE THREAD

**Issue by 64luo** [heyanLE/EasyBangumi#12]

**Comment by 64luo** [comment]
尝试过刷新重新加载，重进app，卸载重装

**Comment by heyanLE** [comment]
应该是 源出了问题，森之屋我记得跑路了，暂时先看樱花的？我这周刚开始投入3.0的开发，估计得下下周才能写完

**Comment by 64luo** [comment]
> 应该是 源出了问题，森之屋我记得跑路了，暂时先看樱花的？我这周刚开始投入3.0的开发，估计得下下周才能写完

okk，了解
